const menu = [
  {
    type: 'CATEGORY',
    id: 'SA4FRWQJS67PZL4ZLKK7KZMO',
    updatedAt: '2022-01-12T23:16:22.294Z',
    version: '1642029382294',
    isDeleted: false,
    presentAtAllLocations: true,
    categoryData: {
      name: 'BREAKFAST',
    },
  },
  {
    type: 'ITEM',
    id: '6VSHRX5KARQJQSFTKONJJT6Y',
    updatedAt: '2022-01-12T23:11:55.766Z',
    version: '1642029115766',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'BACON CARBONERA',
      description: '   ',
      categoryId: 'SA4FRWQJS67PZL4ZLKK7KZMO',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: 'YU5DU5D3C2PSLPHCSGAQ5HBZ',
          updatedAt: '2022-01-12T23:06:58.395Z',
          version: '1642028818395',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: '6VSHRX5KARQJQSFTKONJJT6Y',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '2300',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: 'YU5DU5D3C2PSLPHCSGAQ5HBZ',
    updatedAt: '2022-01-12T23:06:58.395Z',
    version: '1642028818395',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: '6VSHRX5KARQJQSFTKONJJT6Y',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '2300',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'ITEM',
    id: 'EPJRUC6BXCIYMTBH473ZRM5M',
    updatedAt: '2022-01-12T23:09:11.438Z',
    version: '1642028951438',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'HUEVOS AL PLATO CON CHORIZO',
      categoryId: 'SA4FRWQJS67PZL4ZLKK7KZMO',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: '6NABGQ6JKBZKC5L6TRUP6ZWI',
          updatedAt: '2022-01-12T23:09:11.438Z',
          version: '1642028951438',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'EPJRUC6BXCIYMTBH473ZRM5M',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '2400',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: '6NABGQ6JKBZKC5L6TRUP6ZWI',
    updatedAt: '2022-01-12T23:09:11.438Z',
    version: '1642028951438',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'EPJRUC6BXCIYMTBH473ZRM5M',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '2400',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'ITEM',
    id: 'TUIVOEGDY5L4KH4MWUF5C6I2',
    updatedAt: '2022-01-12T23:09:26.076Z',
    version: '1642028966076',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'MIGAS',
      categoryId: 'SA4FRWQJS67PZL4ZLKK7KZMO',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: '4OA6RQFZX3MLSJL7EFGPNC7Y',
          updatedAt: '2022-01-12T23:09:26.076Z',
          version: '1642028966076',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'TUIVOEGDY5L4KH4MWUF5C6I2',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '2400',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: '4OA6RQFZX3MLSJL7EFGPNC7Y',
    updatedAt: '2022-01-12T23:09:26.076Z',
    version: '1642028966076',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'TUIVOEGDY5L4KH4MWUF5C6I2',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '2400',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'CATEGORY',
    id: 'GWHDKWWFSU27NHLOHLFXGVF6',
    updatedAt: '2022-01-12T23:16:30.574Z',
    version: '1642029390574',
    isDeleted: false,
    presentAtAllLocations: true,
    categoryData: {
      name: 'PLATTERS AND TAPAS',
    },
  },
  {
    type: 'ITEM',
    id: '4QZPOL4VNYUA6L6GYUE4FSTL',
    updatedAt: '2022-01-12T23:10:52.681Z',
    version: '1642029052681',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'PLATODEMONTADITOS',
      categoryId: 'GWHDKWWFSU27NHLOHLFXGVF6',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: 'A6KG27JD4NNQPVBTHUG3B6S6',
          updatedAt: '2022-01-12T23:10:52.681Z',
          version: '1642029052681',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: '4QZPOL4VNYUA6L6GYUE4FSTL',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '2000',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: 'A6KG27JD4NNQPVBTHUG3B6S6',
    updatedAt: '2022-01-12T23:10:52.681Z',
    version: '1642029052681',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: '4QZPOL4VNYUA6L6GYUE4FSTL',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '2000',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'ITEM',
    id: 'IN5FJBH7PRHE7XBCB7KPJRWJ',
    updatedAt: '2022-01-12T23:11:09.865Z',
    version: '1642029069865',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'CHARCUTERIA',
      categoryId: 'GWHDKWWFSU27NHLOHLFXGVF6',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: 'UM6XVQKY3SQSF76PS65526FS',
          updatedAt: '2022-01-12T23:11:09.865Z',
          version: '1642029069865',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'IN5FJBH7PRHE7XBCB7KPJRWJ',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '7500',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: 'UM6XVQKY3SQSF76PS65526FS',
    updatedAt: '2022-01-12T23:11:09.865Z',
    version: '1642029069865',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'IN5FJBH7PRHE7XBCB7KPJRWJ',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '7500',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'ITEM',
    id: 'Z625FU5OGWH65XA7LDOEH3LH',
    updatedAt: '2022-01-12T23:15:36.281Z',
    version: '1642029336281',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'CECINA',
      categoryId: 'GWHDKWWFSU27NHLOHLFXGVF6',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: '7KAYP7MWZHWALOFLQSWKOZER',
          updatedAt: '2022-01-12T23:11:34.572Z',
          version: '1642029094572',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'Z625FU5OGWH65XA7LDOEH3LH',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '3500',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: '7KAYP7MWZHWALOFLQSWKOZER',
    updatedAt: '2022-01-12T23:11:34.572Z',
    version: '1642029094572',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'Z625FU5OGWH65XA7LDOEH3LH',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '3500',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'CATEGORY',
    id: 'NDDE7VY3JO6FBUUXGA6GNJNL',
    updatedAt: '2022-01-12T23:12:46.36Z',
    version: '1642029166360',
    isDeleted: false,
    presentAtAllLocations: true,
    categoryData: {
      name: 'TAPAS Y RACIONES',
    },
  },
  {
    type: 'ITEM',
    id: 'YY7KUJUXU7HP32IXV3O3ONQY',
    updatedAt: '2022-01-12T23:12:46.36Z',
    version: '1642029166360',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'PAN CON TOMATE',
      categoryId: 'NDDE7VY3JO6FBUUXGA6GNJNL',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: 'JWXPBS42PL2XXGFVAD372NMS',
          updatedAt: '2022-01-12T23:12:46.36Z',
          version: '1642029166360',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'YY7KUJUXU7HP32IXV3O3ONQY',
            name: 'Regular',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '1200',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: 'JWXPBS42PL2XXGFVAD372NMS',
    updatedAt: '2022-01-12T23:12:46.36Z',
    version: '1642029166360',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'YY7KUJUXU7HP32IXV3O3ONQY',
      name: 'Regular',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '1200',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'ITEM',
    id: 'XZEB35IXQUOXXJM3ETABACYJ',
    updatedAt: '2022-01-12T23:14:57.024Z',
    version: '1642029297024',
    isDeleted: false,
    presentAtAllLocations: true,
    itemData: {
      name: 'TORTILLA ESPANOLA',
      categoryId: 'NDDE7VY3JO6FBUUXGA6GNJNL',
      variations: [
        {
          type: 'ITEM_VARIATION',
          id: 'LH3SVBZJAZIKFOY6IIWEZPUX',
          updatedAt: '2022-01-12T23:14:57.024Z',
          version: '1642029297024',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'XZEB35IXQUOXXJM3ETABACYJ',
            name:
              'TRADITIONAL SPANISH OMELETTE WITH CONFIT POTATOES AND ONIONS',
            ordinal: 1,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '1600',
              currency: 'USD',
            },
            stockable: true,
          },
        },
        {
          type: 'ITEM_VARIATION',
          id: 'SMBXOUJO7VOM2R6YNO3OWWNC',
          updatedAt: '2022-01-12T23:14:57.024Z',
          version: '1642029297024',
          isDeleted: false,
          presentAtAllLocations: true,
          itemVariationData: {
            itemId: 'XZEB35IXQUOXXJM3ETABACYJ',
            name: 'TURKEY CHORIZO',
            ordinal: 2,
            pricingType: 'FIXED_PRICING',
            priceMoney: {
              amount: '2000',
              currency: 'USD',
            },
            stockable: true,
          },
        },
      ],
      productType: 'REGULAR',
      skipModifierScreen: false,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: 'LH3SVBZJAZIKFOY6IIWEZPUX',
    updatedAt: '2022-01-12T23:14:57.024Z',
    version: '1642029297024',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'XZEB35IXQUOXXJM3ETABACYJ',
      name: 'TRADITIONAL SPANISH OMELETTE WITH CONFIT POTATOES AND ONIONS',
      ordinal: 1,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '1600',
        currency: 'USD',
      },
      stockable: true,
    },
  },
  {
    type: 'ITEM_VARIATION',
    id: 'SMBXOUJO7VOM2R6YNO3OWWNC',
    updatedAt: '2022-01-12T23:14:57.024Z',
    version: '1642029297024',
    isDeleted: false,
    presentAtAllLocations: true,
    itemVariationData: {
      itemId: 'XZEB35IXQUOXXJM3ETABACYJ',
      name: 'TURKEY CHORIZO',
      ordinal: 2,
      pricingType: 'FIXED_PRICING',
      priceMoney: {
        amount: '2000',
        currency: 'USD',
      },
      stockable: true,
    },
  },
];

let categories = menu.filter((i) => i.type === 'CATEGORY');
let dbMenu = categories.map((cat) => {
  return {
    name: cat.categoryData.name,
    items: menu
      .filter((i) => i.type === 'ITEM' && i.itemData.categoryId === cat.id)
      .map((i) => {
        return {
          name: i.itemData.name,
          items: i.itemData.variations.map((iv) => {
            return {
              name: iv.itemVariationData.name,
              id: iv.id,
              price: iv.itemVariationData.priceMoney.amount,
            };
          }),
        };
      }),
  };
});

export const menuData = { name: 'Catalog', items: dbMenu };
